version: '3.4'

networks:
  backend:

services:
  sqldata:
    volumes:
    - ./db:/var/opt/mssql/data        
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Numsey#2022
      - ACCEPT_EULA=Y
    ports:
        - 8181:1433
    networks:
        - backend

  educenter.api:
    image: ${DOCKER_REGISTRY-}educenterapi
    build:
      context: .
      dockerfile: EduCenter.Api/Dockerfile
    networks:
        - backend

  apigateway.api:
    image: ${DOCKER_REGISTRY-}apigatewayapi
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    build:
      context: .
      dockerfile: ApiGateway.Api/Dockerfile
    ports:
        - 9999:80
    networks:
        - backend

  sport.api:
    image: ${DOCKER_REGISTRY-}sportapi
    build:
      context: .
      dockerfile: Sport.Api/Dockerfile
    networks:
        - backend


  authtorisation.api:
    image: ${DOCKER_REGISTRY-}authtorisationapi
    build:
      context: .
      dockerfile: Authtorisation.Api/Dockerfile
    networks:
        - backend
